version: '3.3'

services:
  test-app:
    image: fr-api-image
    ports:
      - 3333:3003
    networks:
      - web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./mockoon-fr.json:/mockoon-fr.json

networks:
  web:
    driver: bridge